# Generated by Django 5.0.6 on 2024-06-26 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('rut_abogado', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(default='default@example.com', max_length=255)),
                ('direccion', models.CharField(default='Dirección por defecto', max_length=255)),
                ('telefono', models.CharField(default='123456789', max_length=255)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cliente', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('rut_usuario', models.CharField(max_length=12)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateField()),
                ('leido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TecnicoJuridico',
            fields=[
                ('rut_tecnico', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id_causa', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_causa', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=255)),
                ('abogado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abogados.abogado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abogados.cliente')),
                ('tecnico_juridico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abogados.tecnicojuridico')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_contrato', models.DateField()),
                ('monto_contrato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modalidad_pago', models.CharField(max_length=255)),
                ('observacion', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abogados.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nom_documento', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=255)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='abogados.causa')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pago', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abogados.cliente')),
            ],
        ),
    ]
