# Generated by Django 5.0.6 on 2024-06-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abogados', '0003_solicitudservicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudservicio',
            old_name='usuario',
            new_name='cliente',
        ),
    ]
