# Generated by Django 5.0.6 on 2024-07-02 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abogados', '0004_rename_usuario_solicitudservicio_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='rut_usuario',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='cliente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='abogado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abogados.abogado'),
        ),
    ]
